[pytest]
minversion = "9.0"
addopts = ["-rxXs"]
testpaths = [
    "src/relife/tests",
    "src/relife/datasets/tests",
    "src/relife/lifetime_models/tests",
    "src/relife/stochastic_processes/tests",
    "src/relife/policies/tests",
]
